/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewRouteImport } from './routes/new'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as SSlugResultsRouteImport } from './routes/s.$slug.results'

const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugResultsRoute = SSlugResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => SSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/s/$slug/results': typeof SSlugResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/s/$slug/results': typeof SSlugResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/s/$slug/results': typeof SSlugResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/new' | '/s/$slug' | '/s/$slug/results'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/new' | '/s/$slug' | '/s/$slug/results'
  id: '__root__' | '/' | '/new' | '/s/$slug' | '/s/$slug/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRoute: typeof NewRoute
  SSlugRoute: typeof SSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug/results': {
      id: '/s/$slug/results'
      path: '/results'
      fullPath: '/s/$slug/results'
      preLoaderRoute: typeof SSlugResultsRouteImport
      parentRoute: typeof SSlugRoute
    }
  }
}

interface SSlugRouteChildren {
  SSlugResultsRoute: typeof SSlugResultsRoute
}

const SSlugRouteChildren: SSlugRouteChildren = {
  SSlugResultsRoute: SSlugResultsRoute,
}

const SSlugRouteWithChildren = SSlugRoute._addFileChildren(SSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  SSlugRoute: SSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
